/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simple.gradle.java.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void getSum() {
       int result = App.getSum(10, 12);
       int expected = 22;
       assertEquals(expected,result);
    }

    @Test void getProduct() {
       assertEquals(20, App.getProduct(4, 5));
       assertEquals(0, App.getProduct(7, 0));
       assertEquals(-6, App.getProduct(-2, 3));
    }

    @Test void main(){
        App.main(new String[]{});
    }
}
